name: Node CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "1 4-9/4 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: generate new data
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run generate
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          # github-token: ${{ secrets.TOKEN }}
          branch: "gh-pages"
          commit-message: "chore: publish with new data"
          # force-add: "true"
          # rebase: "true"
          folder: docs
          # files: docs/
          # name: Github Action
          # email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: Github Action
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
